/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
        playfair: ['Playfair Display', 'serif'],
        roboto: ['Roboto', 'sans-serif'],
        montserrat: ['Montserrat', 'sans-serif'],
        lato: ['Lato', 'sans-serif'],
        opensans: ['Open Sans', 'sans-serif'],
        poppins: ['Poppins', 'sans-serif'],
        sourcesans: ['Source Sans Pro', 'sans-serif'],
        merriweather: ['Merriweather', 'serif'],
        oswald: ['Oswald', 'sans-serif'],
        outfit: ['Outfit', 'sans-serif'],
        worksans: ['Work Sans', 'sans-serif'],
        dmsans: ['DM Sans', 'sans-serif'],
        dmserif: ['DM Serif Text', 'serif'],
        nunitosans: ['Nunito Sans', 'sans-serif'],
        quicksand: ['Quicksand', 'sans-serif'],
        lexenddeca: ['Lexend Deca', 'sans-serif'],
        questrial: ['Questrial', 'sans-serif'],
        funnelsans: ['Funnel Sans', 'sans-serif'],
        funneldisplay: ['Funnel Display', 'sans-serif'],
        onest: ['Onest', 'sans-serif'],
        gabarito: ['Gabarito', 'sans-serif'],
        figtree: ['Figtree', 'sans-serif'],
        tomorrow: ['Tomorrow', 'sans-serif'],
        sniglet: ['Sniglet', 'cursive'],
        manrope: ['Manrope', 'sans-serif'],
        archivoblack: ['Archivo Black', 'sans-serif'],
        bebasneue: ['Bebas Neue', 'cursive'],
        fjallaone: ['Fjalla One', 'sans-serif'],
        geist: ['Geist', 'sans-serif'],
        specialgothicexpandedone: ['Special Gothic Expanded One', 'sans-serif'],
        specialgothiccondensedone: ['Special Gothic Condensed One', 'sans-serif'],
        specialgothic: ['Special Gothic', 'sans-serif'],
        nationalpark: ['National Park', 'sans-serif'],
        calsans: ['Cal Sans', 'sans-serif'],
        alansans: ['Alan Sans', 'sans-serif'],
        vendsans: ['Vend Sans', 'sans-serif'],
        asimovian: ['Asimovian', 'sans-serif'],
        sansation: ['Sansation', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [],
}